config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  get 'home/about'
  root 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = current_user.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not Authorized To Edit This Contact" if @contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>First name:</strong>
    <%= contact.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= contact.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= contact.twitter %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> contact couldn't be saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="form-group form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="form-group form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="form-group form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="form-group form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <div class="form-group form-group">
    <%= form.number_field :user_id, id: :contact_user_id, class:"form-control", value: current_user.id, type:'hidden' %>
  </div>

  <div>
    <%= form.submit class:"btn btn-dark mt-2"%>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>
<%= link_to "Delete", @contact, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn mt-2 btn-outline-danger" %>
<br>

<div class="mt-3">
  <%= link_to "Show this contact", @contact, class:"link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %> |
  
  <%= link_to "Back to contacts", contacts_path, class:"link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
</div>

app/views/contacts/index.html.erb
<% if user_signed_in? %>
<h1>All Contacts</h1>
<hr class="border border-dark border-3 opacity-75">

<div id="contacts">
    
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "View Contact", contact, class:"link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
    </p>
  <% end %>
</div>

<%= link_to "+Add a New Contact", new_contact_path, class:"btn btn-success mt-5" %>
<% else %>
<h1>Welcome</h1>
<p>This site allows you to create an account to save contacts and their information.</p>
<p>Please <%= link_to "sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> to continue.


<% end %>

app/views/contacts/new.html.erb
<h1>Add a New Contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold"><%= @contact.first_name%> <%= @contact.last_name %></h1>
    <p class="col-md-8 fs-4"></p>
    <div class="col-md-8">
      <p>
        <%= @contact.email %> |
        <%= @contact.phone %> |
        <%= @contact.twitter %>
      </p> 
      <%= link_to "Edit", edit_contact_path(@contact), class:"btn btn-dark" %>
      <%= link_to "Back", contacts_path, class:"btn btn-dark" %>
    </div>
      <%= button_to "Delete this contact", @contact, method: :delete, class:"btn btn-danger btn-lg mt-5"%>
  </div>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
  <div class="container-fluid">
    <%= link_to "Contacts App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'New Contact', new_contact_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Contacts', contacts_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link"%>
          </li>
        <% end %>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show mt-3" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Contacts App</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header', class:"mb-3 mt-3"%>
    <div class="container">
      <% if notice%>
        <%= render 'layouts/alerts' %>
      <% end%>
      <br />
      <%= yield %>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>